/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Main;

import BusinessReliefPortal.Business.Business;
import BusinessReliefPortal.Enterprise.BusinessEnterprise;
import BusinessReliefPortal.Enterprise.Enterprise;
import BusinessReliefPortal.Network.Network;
import BusinessReliefPortal.Organization.Organization;
import static UserInterface.Main.LoginPage.system;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ishitajanwale
 */
public class BusinessEnterprisePage extends javax.swing.JFrame {

    /**
     * Creates new form BusinessEnterprisePage
     */
    public BusinessEnterprisePage() {
        initComponents();
        system = LoginPage.system;
        // system = dB4OUtil.retrieveSystem();
        popBusinessTab();
        txtBusinessID.setText(String.valueOf(Business.getCount()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ViewBTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtVBusinessID = new javax.swing.JTextField();
        txtVBusinessName = new javax.swing.JTextField();
        txtVBusinessDesc = new javax.swing.JTextField();
        txtVBusinessLoc = new javax.swing.JTextField();
        RbtnVEssBusiness = new javax.swing.JRadioButton();
        RbtnVNonEssBusiness = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        PanelViewBusiness = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBusinessID = new javax.swing.JTextField();
        txtBusinessLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBusinessDescription = new javax.swing.JTextArea();
        btnAddBusiness = new javax.swing.JButton();
        RbtnEssBusiness = new javax.swing.JRadioButton();
        rbNonessBusiness = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtBusinessLocation1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBusinessName = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jTabbedPane1.setRequestFocusEnabled(false);

        ViewBTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Business ID", "Business Name", "Business Description", "Business Type", "Business Location"
            }
        ));
        jScrollPane5.setViewportView(ViewBTable);

        jLabel7.setText("Business ID");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Business Name");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Business Description");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Business Location");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        RbtnVEssBusiness.setText("Essential Business");
        RbtnVEssBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnVEssBusinessActionPerformed(evt);
            }
        });

        RbtnVNonEssBusiness.setText("Non-Essential Business");
        RbtnVNonEssBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnVNonEssBusinessActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel12.setText("Business Type");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtVBusinessDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtVBusinessID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtVBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(txtVBusinessLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(RbtnVEssBusiness)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RbtnVNonEssBusiness)))
                        .addContainerGap(439, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVBusinessID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVBusinessDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbtnVEssBusiness)
                    .addComponent(RbtnVNonEssBusiness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVBusinessLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("View Businesses", jPanel3);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 171, 214));
        jLabel1.setText("Business ID");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 171, 214));
        jLabel2.setText("Business Description");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 171, 214));
        jLabel3.setText("Business Type");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 171, 214));
        jLabel4.setText("Business Location");

        txtBusinessID.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessID.setForeground(new java.awt.Color(255, 255, 255));

        txtBusinessLocation.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessLocation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessLocation.setForeground(new java.awt.Color(255, 255, 255));

        txtBusinessDescription.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessDescription.setColumns(20);
        txtBusinessDescription.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessDescription.setForeground(new java.awt.Color(255, 255, 255));
        txtBusinessDescription.setRows(5);
        jScrollPane1.setViewportView(txtBusinessDescription);

        btnAddBusiness.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAddBusiness.setForeground(new java.awt.Color(0, 171, 214));
        btnAddBusiness.setText("Add ");
        btnAddBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBusinessActionPerformed(evt);
            }
        });

        RbtnEssBusiness.setText("Essential Business");
        RbtnEssBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnEssBusinessActionPerformed(evt);
            }
        });

        rbNonessBusiness.setText("Non-Essential Business");
        rbNonessBusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNonessBusinessActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 171, 214));
        jLabel5.setText("Organization Type");

        txtBusinessLocation1.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessLocation1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessLocation1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 171, 214));
        jLabel6.setText("Business Name");

        txtBusinessName.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessName.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelViewBusinessLayout = new javax.swing.GroupLayout(PanelViewBusiness);
        PanelViewBusiness.setLayout(PanelViewBusinessLayout);
        PanelViewBusinessLayout.setHorizontalGroup(
            PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelViewBusinessLayout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBusinessName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBusinessID, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                                            .addComponent(RbtnEssBusiness)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbNonessBusiness))))
                                .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(txtBusinessLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelViewBusinessLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtBusinessLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(btnAddBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        PanelViewBusinessLayout.setVerticalGroup(
            PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusinessID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelViewBusinessLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusinessLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RbtnEssBusiness)
                        .addComponent(rbNonessBusiness)))
                .addGap(40, 40, 40)
                .addGroup(PanelViewBusinessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusinessLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnAddBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Business", PanelViewBusiness);

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtnVNonEssBusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnVNonEssBusinessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnVNonEssBusinessActionPerformed

    private void RbtnVEssBusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnVEssBusinessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnVEssBusinessActionPerformed

    private void rbNonessBusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNonessBusinessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNonessBusinessActionPerformed

    private void RbtnEssBusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnEssBusinessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbtnEssBusinessActionPerformed

    private void btnAddBusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBusinessActionPerformed
        // TODO add your handling code here:
        try {

            for (Network nw : system.getNetworkList()) {
                if ("Boston".equals(nw.getNetworkName())) {
                    for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
                        if (ent.getEnterpriseType() == Enterprise.EnterpriseType.BUSINESSENTERPRISE) {
                            BusinessEnterprise busEnt = (BusinessEnterprise) ent;
                            // Business addBusObj = busEnt.addBusiness(Integer.parseInt(txtBusinessID.getText()));
                            int latestBusID = Integer.parseInt(txtBusinessID.getText());
                            Business addBusObj = busEnt.addBusinesses(Integer.parseInt(txtBusinessID.getText()));
                            addBusObj.setBusinessDescription(txtBusinessDescription.getText());
                            addBusObj.setBusinessName(txtBusinessName.getText());
                            if (RbtnEssBusiness.isSelected()) {
                                addBusObj.setBusinessType("Essential");
                            }
                            if (rbNonessBusiness.isSelected()) {
                                addBusObj.setBusinessType("NonEssential");
                            }
                            addBusObj.setOrgType(Organization.Type.PUBLICBUSINESSPORTFOLIOORG);
                            txtBusinessDescription.setText("");
                            txtBusinessName.setText("");
                            latestBusID+=1;
                            txtBusinessID.setText(String.valueOf(latestBusID));
                            return;
                        }
                    }
                }
            }
        } catch (java.lang.NullPointerException ne) {
        }
    }//GEN-LAST:event_btnAddBusinessActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = ViewBTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select row to view the details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) ViewBTable.getModel();
        Business B = (Business) model.getValueAt(selectedRowIndex, 1);
        txtVBusinessID.setText(String.valueOf(B.getBusinessId()));
        txtVBusinessID.setEditable(false);
        txtVBusinessName.setText(String.valueOf(B.getBusinessName()));
        txtVBusinessName.setEditable(false);
        txtVBusinessDesc.setText(String.valueOf(B.getBusinessDescription()));
        txtVBusinessDesc.setEditable(false);

        txtVBusinessLoc.setText(String.valueOf(B.getBusinessLocation()));
        txtVBusinessLoc.setEditable(false);
    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusinessEnterprisePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusinessEnterprisePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusinessEnterprisePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusinessEnterprisePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusinessEnterprisePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelViewBusiness;
    private javax.swing.JRadioButton RbtnEssBusiness;
    private javax.swing.JRadioButton RbtnVEssBusiness;
    private javax.swing.JRadioButton RbtnVNonEssBusiness;
    private javax.swing.JTable ViewBTable;
    private javax.swing.JButton btnAddBusiness;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbNonessBusiness;
    private javax.swing.JTextArea txtBusinessDescription;
    private javax.swing.JTextField txtBusinessID;
    private javax.swing.JTextField txtBusinessLocation;
    private javax.swing.JTextField txtBusinessLocation1;
    private javax.swing.JTextField txtBusinessName;
    private javax.swing.JTextField txtVBusinessDesc;
    private javax.swing.JTextField txtVBusinessID;
    private javax.swing.JTextField txtVBusinessLoc;
    private javax.swing.JTextField txtVBusinessName;
    // End of variables declaration//GEN-END:variables

    private void popBusinessTab() {
        DefaultTableModel model = (DefaultTableModel) ViewBTable.getModel();
        model.setRowCount(0);

        for (Network nw : system.getNetworkList()) {
            if ("Boston".equals(nw.getNetworkName())) {
                for (Enterprise en : nw.getEntDirObj().getEnterpriseList()) {
                    if (en.getEnterpriseType() == Enterprise.EnterpriseType.BUSINESSENTERPRISE) {
                        BusinessEnterprise busEnt = (BusinessEnterprise) en;
                        ArrayList<Business> businessList = busEnt.getBusinessDir();
                        for (Business bus : businessList) {
                            Object[] row = new Object[5];
                            row[0] = bus.getBusinessId();
                            row[1] = bus.getBusinessName();
                            row[2] = bus.getBusinessDescription();
                            row[3] = bus.getBusinessType();
                            row[4] = bus.getBusinessLocation();

                            model.addRow(row);

                        }
                    }
                }
            }
        }

    }

}
