/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Main;

import Business.DB4OUtil.DB4OUtil;
import BusinessReliefPortal.BusinessReliefSystem;
import BusinessReliefPortal.ConfigureBusinessPortal;
import BusinessReliefPortal.Employee.Employee;
import BusinessReliefPortal.Enterprise.Enterprise;
import BusinessReliefPortal.Enterprise.UserAndVerificationEnterprise;
import BusinessReliefPortal.Lender.Lender;
import BusinessReliefPortal.Lender.LenderDirectory;
import BusinessReliefPortal.Network.Network;
import BusinessReliefPortal.UserAccount.UserAccount;
import BusinessReliefPortal.UserAccount.UserAccount.RoleType;
import static UserInterface.Main.LenderPage.lenderID;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author ishitajanwale
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public static BusinessReliefSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public LoginPage() {
        initComponents();

        cbUserType.removeAllItems();
        for (RoleType role : UserAccount.RoleType.values()) {
            cbUserType.addItem(role.getValue());
        }
    }

    public void close() {
        dB4OUtil.storeSystem(system);
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        lblPaneHeading = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cbUserType = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblRegistration = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));

        LoginPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        LoginPanel.setMinimumSize(new java.awt.Dimension(1000, 1000));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPaneHeading.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        lblPaneHeading.setForeground(new java.awt.Color(0, 75, 126));
        lblPaneHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaneHeading.setText("Business Relief Portal");
        LoginPanel.add(lblPaneHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 540, 150));

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 75, 126));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Username");
        LoginPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 260, 70));

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 75, 126));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");
        LoginPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 270, 70));

        lblUserType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(0, 75, 126));
        lblUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Requiredlibraries/users.png"))); // NOI18N
        lblUserType.setText("User Type");
        LoginPanel.add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 220, 60));

        txtUsername.setBackground(new java.awt.Color(0, 151, 201));
        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        LoginPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 300, 43));

        cbUserType.setBackground(new java.awt.Color(0, 151, 201));
        cbUserType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        cbUserType.setForeground(new java.awt.Color(255, 255, 255));
        cbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Treasurer", "Government", "Borrower", "Lender", "Employee", "Public Business Admin", "Proposal Admin" }));
        LoginPanel.add(cbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 300, 44));

        btnLogin.setBackground(new java.awt.Color(0, 151, 201));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Sign in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        LoginPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 210, 40));

        btnClose.setBackground(new java.awt.Color(204, 0, 51));
        btnClose.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        LoginPanel.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, -1));

        txtPassword.setBackground(new java.awt.Color(0, 151, 201));
        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        LoginPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 300, 44));

        lblRegistration.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblRegistration.setForeground(new java.awt.Color(0, 112, 169));
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setText("First time User? Please register below first.");
        LoginPanel.add(lblRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 415, -1));

        btnRegister.setBackground(new java.awt.Color(0, 151, 201));
        btnRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Sign up");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        LoginPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Requiredlibraries/Bg.jpg"))); // NOI18N
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the username");
        } else if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Password");
        } else if (cbUserType.getSelectedItem().equals("Select User Type")) {
            JOptionPane.showMessageDialog(rootPane, "Please select a User Type");
        }

        String userName = txtUsername.getText();
        String pasword = txtPassword.getText();
        String role = (String) cbUserType.getSelectedItem();

        for (Network nw : system.getNetworkList()) {
            if ("Boston".equals(nw.getNetworkName())) {
                Map<Integer, UserAccount> userAccountsNetwork = nw.getUserAccountsNetwork();
                for (Map.Entry<Integer, UserAccount> entry : userAccountsNetwork.entrySet()) {
                    Object key = entry.getKey();
                    Object val = entry.getValue();

                    if (entry.getValue().getUserName().equals(userName) || entry.getValue().getPassword().equals(pasword) || entry.getValue().getRoleType().getValue().equals(role)) {
                        if (role.equals(RoleType.SYSTEADMIN.getValue())) {
                            SystemAdminPage page = new SystemAdminPage();
                            page.setVisible(true);

                        } else if (role.equals(RoleType.TREASURER.getValue())) {
                            TreasurerPage page = new TreasurerPage();
                            page.setVisible(true);

                        } else if (role.equals(RoleType.FUNDMANAGER.getValue())) {
                            FundManagerPage page = new FundManagerPage();
                            page.setVisible(true);

                        } else if (role.equals(RoleType.PUBLICBUSINESSADMIN.getValue())) {
                            PublicBusinessPage page = new PublicBusinessPage();
                            page.setVisible(true);

                        } else if (role.equals(RoleType.PROPOSALADMIN.getValue())) {
                            ProposalValidationPage page = new ProposalValidationPage();
                            page.setVisible(true);

                        } else if (role.equals(RoleType.QUERYMANAGER.getValue())) {
                            QueryManagerPage page = new QueryManagerPage();
                            page.setVisible(true);

                        } else if (role.equals(RoleType.VALIDATOR.getValue())) {
                            ValidatorPage page = new ValidatorPage();
                            page.setVisible(true);

                        } else if (role.equals(RoleType.LENDER.getValue())) {
                            LenderPage page = new LenderPage(userName);
                            page.setVisible(true);

                        } else if (role.equals(RoleType.BORROWER.getValue())) {
                            BorrowerPage page = new BorrowerPage(userName);
                            page.setVisible(true);

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Please check your credentials");
                        }
                        dispose();
                        return;
                    }

                }
            }
        }

//        if (cbUserType.getSelectedItem().equals("Lender")) {
//            boolean userfoundstatus = false;
//            for (Network nw : system.getNetworkList()) {
//                if ("Boston".equalsIgnoreCase(nw.getNetworkName())) {
//                    for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
//                        if (ent.getEnterpriseType() == Enterprise.EnterpriseType.USERANDVERIFICATIONENTERPRISE) {
//                            UserAndVerificationEnterprise userEnt = (UserAndVerificationEnterprise) ent;
//                            for (Lender len : userEnt.getLenderDirectory()) {
//                                if (len.getUserAccount().getUserName().equalsIgnoreCase(txtUsername.getText())
//                                        && len.getUserAccount().getPassword().equalsIgnoreCase(txtPassword.getText())) {
//                                    userfoundstatus = true;
////                                               
//                                    if ("Rejected".equalsIgnoreCase(len.getActiveStatus())) {
//                                        JOptionPane.showMessageDialog(rootPane, "Sorry! Your Lender status is Rejected");
//                                        return;
//                                    }
////                                                    }
////                                                }
//                                    LenderPage lenderPage = new LenderPage(txtUsername.getText());
//
//                                    lenderPage.setVisible(true);
//                                    //JOptionPane.showMessageDialog(rootPane, "Successfully Logged in");
//                                    dispose();
//                                }
//                            }
//                        }
//                    }
//                }
//            }
//            if (!userfoundstatus) {
//                JOptionPane.showMessageDialog(rootPane, "No such Lender found");
//            }
//
//        } // This part will be used to check Borrower Login credentials
//        else if (cbUserType.getSelectedItem().equals("Borrower")) {
//            boolean userfoundstatus = false;
//            for (Network nw : system.getNetworkList()) {
//                if ("Boston".equalsIgnoreCase(nw.getNetworkName())) {
//                    for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
//                        if (ent.getEnterpriseType() == Enterprise.EnterpriseType.USERANDVERIFICATIONENTERPRISE) {
//                            UserAndVerificationEnterprise userEnt = (UserAndVerificationEnterprise) ent;
//                            for (UserAccount usercred : userEnt.getUserAccountDirectory().getUserAccountList()) {
//                                if (usercred.getUserName().equalsIgnoreCase(txtUsername.getText())
//                                        && usercred.getPassword().equalsIgnoreCase(txtPassword.getText())) {
//                                    userfoundstatus = true;
//                                    BorrowerPage bp = new BorrowerPage(usercred.getUserName());
//                                    bp.setVisible(true);
//                                    //JOptionPane.showMessageDialog(rootPane, "Successfully Logged in");
//                                    dispose();
//                                }
//                            }
//                        }
//                    }
//                }
//            }
//            if (!userfoundstatus) {
//                JOptionPane.showMessageDialog(rootPane, "No such Borrower found");
//            }
//
//        } else if (cbUserType.getSelectedItem().equals("Business Admin")) {
//            BusinessEnterprisePage bep = new BusinessEnterprisePage();
//            bep.setVisible(true);
//        } 
//        else {
//            JOptionPane.showMessageDialog(rootPane, "Please check your credentials");
//        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        UserRegistrationPage urg = new UserRegistrationPage();
        urg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
        // system = ConfigureBusinessPortal.configure();

        system = DB4OUtil.getInstance().retrieveSystem();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPaneHeading;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
