/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Main;

import Business.DB4OUtil.DB4OUtil;
import BusinessReliefPortal.Business.Business;
import BusinessReliefPortal.Enterprise.BusinessEnterprise;
import BusinessReliefPortal.Enterprise.Enterprise;
import BusinessReliefPortal.Network.Network;
import BusinessReliefPortal.Organization.Organization;
import BusinessReliefPortal.Organization.TreasuryOrg;
import BusinessReliefPortal.Proposal.Proposal;
import BusinessReliefPortal.Proposal.ProposalDirectory;
import java.util.ArrayList;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ritvikparamkusham
 */
public class PublicBusinessPage extends javax.swing.JFrame {

    BusinessReliefPortal.BusinessReliefSystem system;
    BusinessEnterprise busEnt = new BusinessEnterprise();

    /**
     * Creates new form PublicBusinessPage
     */
    public PublicBusinessPage() {
        initComponents();
        system = LoginPage.system;
        // system = dB4OUtil.retrieveSystem();
        popBusinessTab();

        popBusinessProposals();
     

        //dB4OUtil.storeSystem(system);
        txtBusinessId.setText(String.valueOf(busEnt.getLatestBusinessID()));

//        for (Network nw : system.getNetworkList()) {
//            if ("Boston".equals(nw.getNetworkName())) {
//                for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
//                    if (ent.getEnterpriseType() == Enterprise.EnterpriseType.BUSINESSENTERPRISE) {
//                        BusinessEnterprise busEnt = (BusinessEnterprise) ent;
//                        ArrayList<Business> businessDir = busEnt.getBusinessDir();
//                        int size = businessDir.size() - 1;
//                        int lastBusID = businessDir.get(size).getBusinessId();
//
//                        txtBusId.setText(String.valueOf(lastBusID));
//
//                    }
//                }
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panBusiness = new javax.swing.JTabbedPane();
        panViewBusiness = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabBusinessView = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBusDesUpd = new javax.swing.JTextField();
        txtBusNameUpd = new javax.swing.JTextField();
        lblBusName1 = new javax.swing.JLabel();
        lblBusType1 = new javax.swing.JLabel();
        jrbEssBusUpd = new javax.swing.JRadioButton();
        jrbNonEssBusUpd = new javax.swing.JRadioButton();
        txtBusLenderId = new javax.swing.JTextField();
        lblBusLoc1 = new javax.swing.JLabel();
        btnUpdateBusines = new javax.swing.JButton();
        txtbusinessIdInvisible = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        panAddBusiness = new javax.swing.JPanel();
        lblBusID = new javax.swing.JLabel();
        txtBusinessId = new javax.swing.JTextField();
        lblBusName = new javax.swing.JLabel();
        lblBusType = new javax.swing.JLabel();
        lblBusOrgType = new javax.swing.JLabel();
        lblBusLoc = new javax.swing.JLabel();
        txtBusinessName = new javax.swing.JTextField();
        txtBusOrgType = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jrbEssBus = new javax.swing.JRadioButton();
        jrbNonEssBus = new javax.swing.JRadioButton();
        btnAddBusPubOrg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBusinessDes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panFundsUtilization = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabBusinessProposals = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        panViewBusiness.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panViewBusinessFocusGained(evt);
            }
        });
        panViewBusiness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panViewBusinessMouseClicked(evt);
            }
        });
        panViewBusiness.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabBusinessView.setBackground(new java.awt.Color(0, 171, 214));
        tabBusinessView.setForeground(new java.awt.Color(255, 255, 255));
        tabBusinessView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BusinessID", "Name", "Description", "Type", "Lender ID"
            }
        ));
        tabBusinessView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabBusinessViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabBusinessView);

        panViewBusiness.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 1002, 298));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 171, 214));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/document.png"))); // NOI18N
        jLabel2.setText("Business Description:");
        panViewBusiness.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        txtBusDesUpd.setBackground(new java.awt.Color(0, 171, 214));
        txtBusDesUpd.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtBusDesUpd.setForeground(new java.awt.Color(255, 255, 255));
        panViewBusiness.add(txtBusDesUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 465, 250, 40));

        txtBusNameUpd.setBackground(new java.awt.Color(0, 171, 214));
        txtBusNameUpd.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtBusNameUpd.setForeground(new java.awt.Color(255, 255, 255));
        panViewBusiness.add(txtBusNameUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 364, 250, 40));

        lblBusName1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusName1.setForeground(new java.awt.Color(0, 171, 214));
        lblBusName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBusName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/business.png"))); // NOI18N
        lblBusName1.setText("Business Name:");
        panViewBusiness.add(lblBusName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 363, 257, -1));

        lblBusType1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusType1.setForeground(new java.awt.Color(0, 171, 214));
        lblBusType1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBusType1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/type.png"))); // NOI18N
        lblBusType1.setText("Business Type:");
        panViewBusiness.add(lblBusType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 257, -1));

        jrbEssBusUpd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jrbEssBusUpd.setText("Essential ");
        jrbEssBusUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEssBusUpdActionPerformed(evt);
            }
        });
        panViewBusiness.add(jrbEssBusUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 97, -1));

        jrbNonEssBusUpd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jrbNonEssBusUpd.setText("Non-Essential");
        jrbNonEssBusUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNonEssBusUpdActionPerformed(evt);
            }
        });
        panViewBusiness.add(jrbNonEssBusUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, -1, -1));

        txtBusLenderId.setEditable(false);
        txtBusLenderId.setBackground(new java.awt.Color(0, 171, 214));
        txtBusLenderId.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtBusLenderId.setForeground(new java.awt.Color(255, 255, 255));
        panViewBusiness.add(txtBusLenderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 250, 40));

        lblBusLoc1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusLoc1.setForeground(new java.awt.Color(0, 171, 214));
        lblBusLoc1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBusLoc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/id-card.png"))); // NOI18N
        lblBusLoc1.setText("Lender ID");
        panViewBusiness.add(lblBusLoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 257, -1));

        btnUpdateBusines.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnUpdateBusines.setForeground(new java.awt.Color(0, 171, 214));
        btnUpdateBusines.setText("Update Business");
        btnUpdateBusines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBusinesActionPerformed(evt);
            }
        });
        panViewBusiness.add(btnUpdateBusines, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 720, 292, 37));

        txtbusinessIdInvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/istockphoto-1281736074-612x612 (1).jpg"))); // NOI18N
        panViewBusiness.add(txtbusinessIdInvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 1010, 1010));

        jTextField1.setText("jTextField1");
        panViewBusiness.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 700, -1, -1));

        panBusiness.addTab("View Business", panViewBusiness);

        panAddBusiness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panAddBusinessMouseClicked(evt);
            }
        });
        panAddBusiness.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBusID.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusID.setForeground(new java.awt.Color(0, 171, 214));
        lblBusID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/id-card (1).png"))); // NOI18N
        lblBusID.setText("Business ID:");
        panAddBusiness.add(lblBusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 79, 297, -1));

        txtBusinessId.setEditable(false);
        txtBusinessId.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessId.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessId.setForeground(new java.awt.Color(255, 255, 255));
        txtBusinessId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusinessIdActionPerformed(evt);
            }
        });
        panAddBusiness.add(txtBusinessId, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 94, 271, 40));

        lblBusName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusName.setForeground(new java.awt.Color(0, 171, 214));
        lblBusName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/business.png"))); // NOI18N
        lblBusName.setText("Business Name:");
        panAddBusiness.add(lblBusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 180, 308, -1));

        lblBusType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusType.setForeground(new java.awt.Color(0, 171, 214));
        lblBusType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/type.png"))); // NOI18N
        lblBusType.setText("Business Type:");
        panAddBusiness.add(lblBusType, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 382, 297, -1));

        lblBusOrgType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusOrgType.setForeground(new java.awt.Color(0, 171, 214));
        lblBusOrgType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusOrgType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teamwork.png"))); // NOI18N
        lblBusOrgType.setText("Organization Type:");
        panAddBusiness.add(lblBusOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 297, -1));

        lblBusLoc.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBusLoc.setForeground(new java.awt.Color(0, 171, 214));
        lblBusLoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBusLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pin.png"))); // NOI18N
        lblBusLoc.setText("Location:");
        panAddBusiness.add(lblBusLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 297, -1));

        txtBusinessName.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessName.setForeground(new java.awt.Color(255, 255, 255));
        panAddBusiness.add(txtBusinessName, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 185, 271, 40));

        txtBusOrgType.setEditable(false);
        txtBusOrgType.setBackground(new java.awt.Color(0, 171, 214));
        txtBusOrgType.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusOrgType.setForeground(new java.awt.Color(255, 255, 255));
        txtBusOrgType.setText("Public Business Organization");
        panAddBusiness.add(txtBusOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 494, 270, 40));

        jTextField5.setBackground(new java.awt.Color(0, 171, 214));
        jTextField5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Maps to be added");
        panAddBusiness.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 269, 40));

        jrbEssBus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jrbEssBus.setText("Essential ");
        jrbEssBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEssBusActionPerformed(evt);
            }
        });
        panAddBusiness.add(jrbEssBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 398, -1, 37));

        jrbNonEssBus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jrbNonEssBus.setText("Non-Essential");
        jrbNonEssBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNonEssBusActionPerformed(evt);
            }
        });
        panAddBusiness.add(jrbNonEssBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 397, 135, 39));

        btnAddBusPubOrg.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAddBusPubOrg.setForeground(new java.awt.Color(0, 171, 214));
        btnAddBusPubOrg.setText("Add Business to Public Organization");
        btnAddBusPubOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBusPubOrgActionPerformed(evt);
            }
        });
        panAddBusiness.add(btnAddBusPubOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 690, -1, 44));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 171, 214));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/document.png"))); // NOI18N
        jLabel1.setText("Business Description:");
        panAddBusiness.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 297, -1));

        txtBusinessDes.setBackground(new java.awt.Color(0, 171, 214));
        txtBusinessDes.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBusinessDes.setForeground(new java.awt.Color(255, 255, 255));
        panAddBusiness.add(txtBusinessDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 282, 271, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/istockphoto-1281736074-612x612 (1).jpg"))); // NOI18N
        panAddBusiness.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 940));

        panBusiness.addTab("Add Business", panAddBusiness);

        panFundsUtilization.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabBusinessProposals.setBackground(new java.awt.Color(0, 171, 214));
        tabBusinessProposals.setForeground(new java.awt.Color(255, 255, 255));
        tabBusinessProposals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Business ID", "Proposal ID", "Funder ID", "Funds being used"
            }
        ));
        jScrollPane2.setViewportView(tabBusinessProposals);

        panFundsUtilization.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 798, 320));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white-bright-abstract-background-vector-20802409.jpg"))); // NOI18N
        panFundsUtilization.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 970));

        panBusiness.addTab("Funds Utilization ", panFundsUtilization);

        jPanel2.setBackground(new java.awt.Color(0, 171, 214));

        btnLogOut.setBackground(new java.awt.Color(0, 171, 214));
        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout (3).png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Public Business Page");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBusiness)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusinessIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusinessIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusinessIdActionPerformed

    private void btnAddBusPubOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBusPubOrgActionPerformed
        // TODO add your handling code here:
        //  BusinessEnterprise businessEnt = system.getNetworkList()
        
        if (txtBusinessName.getText()==null||txtBusinessDes.getText()==null) {
           JOptionPane.showMessageDialog(rootPane, "Please check if all  business fields are checked");
        }
        
        try {

            for (Network nw : system.getNetworkList()) {
                if ("Boston".equals(nw.getNetworkName())) {
                    for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
                        if (ent.getEnterpriseType() == Enterprise.EnterpriseType.BUSINESSENTERPRISE) {
                            BusinessEnterprise busEnt = (BusinessEnterprise) ent;

                            int latestBusID = Integer.parseInt(txtBusinessId.getText());
                            Business addBusObj = busEnt.addBusinesses(Integer.parseInt(txtBusinessId.getText()));

                            addBusObj.setBusinessDescription(txtBusinessDes.getText());
                            addBusObj.setBusinessName(txtBusinessName.getText());
                            if (jrbEssBus.isSelected()) {
                                addBusObj.setBusinessType("Essential");
                            }
                            if (jrbNonEssBus.isSelected()) {
                                addBusObj.setBusinessType("NonEssential");
                            }
                            addBusObj.setOrgType(Organization.Type.PUBLICBUSINESSPORTFOLIOORG);
                            txtBusinessDes.setText("");
                            txtBusinessName.setText("");
                            latestBusID += 1;
                            txtBusinessId.setText(String.valueOf(latestBusID));
                            popBusinessTab();
                            return;
                        }
                    }
                }
            }
        } catch (java.lang.NullPointerException ne) {
        }


    }//GEN-LAST:event_btnAddBusPubOrgActionPerformed

    private void jrbEssBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEssBusActionPerformed
        // TODO add your handling code here:
        jrbNonEssBus.setSelected(false);
    }//GEN-LAST:event_jrbEssBusActionPerformed

    private void jrbNonEssBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNonEssBusActionPerformed
        // TODO add your handling code here:
        jrbEssBus.setSelected(false);
    }//GEN-LAST:event_jrbNonEssBusActionPerformed

    private void panAddBusinessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panAddBusinessMouseClicked
        // TODO add your handling code here:
        // txtBusId.setText(String.valueOf(Business.getCount()));
    }//GEN-LAST:event_panAddBusinessMouseClicked

    private void panViewBusinessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panViewBusinessMouseClicked
        // TODO add your handling code here:
        //popBusinessTab();
    }//GEN-LAST:event_panViewBusinessMouseClicked

    private void panViewBusinessFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panViewBusinessFocusGained
        // TODO add your handling code here:
        //   popBusinessTab();
    }//GEN-LAST:event_panViewBusinessFocusGained

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:

        // dB4OUtil.storeSystem(system);
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnUpdateBusinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBusinesActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tabBusinessView.getSelectionModel().getLeadSelectionIndex();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(rootPane, "Please select a row to Update");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tabBusinessView.getModel();

        Vector<Vector> dataVector;
        dataVector = model.getDataVector();

        int busIdFromTable = Integer.parseInt(txtbusinessIdInvisible.getText());
        String busName = txtBusNameUpd.getText();
        String busDesc = txtBusDesUpd.getText();

        try {

            for (Network nw : system.getNetworkList()) {
                if ("Boston".equals(nw.getNetworkName())) {
                    for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
                        if (ent.getEnterpriseType() == Enterprise.EnterpriseType.BUSINESSENTERPRISE) {
                            BusinessEnterprise busEnt = (BusinessEnterprise) ent;

                            for (Business updateBus : busEnt.getBusinessDir()) {
                                if (updateBus.getBusinessId() == busIdFromTable) {
                                    updateBus.setBusinessDescription(busDesc);
                                    updateBus.setBusinessName(busName);
                                    if (jrbEssBusUpd.isSelected()) {
                                        
                                        updateBus.setBusinessType("Essential");
                                    }
                                    if (jrbNonEssBusUpd.isSelected()) {
                                        updateBus.setBusinessType("NonEssential");
                                    }
                                }
                            }

                            popBusinessTab();
                            return;
                        }
                    }
                }
            }
        } catch (java.lang.NullPointerException ne) {
        }


    }//GEN-LAST:event_btnUpdateBusinesActionPerformed

    private void tabBusinessViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBusinessViewMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tabBusinessView.getSelectionModel().getLeadSelectionIndex();

        if (selectedRowIndex < 0) {

            return;
        }

        DefaultTableModel model = (DefaultTableModel) tabBusinessView.getModel();

        Vector<Vector> dataVector;
        dataVector = model.getDataVector();

        int busId = (int) dataVector.get(selectedRowIndex).get(0);
        String busName = (String) dataVector.get(selectedRowIndex).get(1);
        String busDesc = (String) dataVector.get(selectedRowIndex).get(2);
        String busType = (String) dataVector.get(selectedRowIndex).get(3);
        String busLenderID = (String) dataVector.get(selectedRowIndex).get(4);

        txtbusinessIdInvisible.setText(String.valueOf(busId));
        txtBusNameUpd.setText(String.valueOf(busName));
        txtBusDesUpd.setText(busDesc);
        txtBusLenderId.setText(busLenderID);

        if ("Essential".equalsIgnoreCase(busType)) {
            jrbEssBusUpd.setSelected(true);
            jrbNonEssBusUpd.setSelected(false);

        } else if ("NonEssential".equalsIgnoreCase(busType)) {
            jrbEssBusUpd.setSelected(false);
            jrbNonEssBusUpd.setSelected(true);
        }
    }//GEN-LAST:event_tabBusinessViewMouseClicked

    private void jrbEssBusUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEssBusUpdActionPerformed
        // TODO add your handling code here:
        jrbNonEssBusUpd.setSelected(false);
    }//GEN-LAST:event_jrbEssBusUpdActionPerformed

    private void jrbNonEssBusUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNonEssBusUpdActionPerformed
        // TODO add your handling code here:
        jrbEssBusUpd.setSelected(false);
    }//GEN-LAST:event_jrbNonEssBusUpdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublicBusinessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublicBusinessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublicBusinessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublicBusinessPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublicBusinessPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBusPubOrg;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUpdateBusines;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JRadioButton jrbEssBus;
    private javax.swing.JRadioButton jrbEssBusUpd;
    private javax.swing.JRadioButton jrbNonEssBus;
    private javax.swing.JRadioButton jrbNonEssBusUpd;
    private javax.swing.JLabel lblBusID;
    private javax.swing.JLabel lblBusLoc;
    private javax.swing.JLabel lblBusLoc1;
    private javax.swing.JLabel lblBusName;
    private javax.swing.JLabel lblBusName1;
    private javax.swing.JLabel lblBusOrgType;
    private javax.swing.JLabel lblBusType;
    private javax.swing.JLabel lblBusType1;
    private javax.swing.JPanel panAddBusiness;
    private javax.swing.JTabbedPane panBusiness;
    private javax.swing.JPanel panFundsUtilization;
    private javax.swing.JPanel panViewBusiness;
    private javax.swing.JTable tabBusinessProposals;
    private javax.swing.JTable tabBusinessView;
    private javax.swing.JTextField txtBusDesUpd;
    private javax.swing.JTextField txtBusLenderId;
    private javax.swing.JTextField txtBusNameUpd;
    private javax.swing.JTextField txtBusOrgType;
    private javax.swing.JTextField txtBusinessDes;
    private javax.swing.JTextField txtBusinessId;
    private javax.swing.JTextField txtBusinessName;
    private javax.swing.JLabel txtbusinessIdInvisible;
    // End of variables declaration//GEN-END:variables

    private void popBusinessProposals() {
        DefaultTableModel model = (DefaultTableModel) tabBusinessProposals.getModel();
        model.setRowCount(0);

        for (Network nw : system.getNetworkList()) {
            if ("Boston".equals(nw.getNetworkName())) {
                ArrayList<Proposal> proposalDirectory = nw.getProposalDirectory().getProposalDirectory(); 
                try {
                    for (Proposal proposal : proposalDirectory) {
                        if("Funds Allocated".equalsIgnoreCase(proposal.getProposalStatus())){
                            Object[] row = new Object[5];
                            row[0] = proposal.getBusinessIdByFunder();
                            row[1] = proposal.getProposalId();
                            row[2] = proposal.getFunderId();
                            row[3] = proposal.getRequestedFundAmount();
                           model.addRow(row);
                        }
                    }
                } catch (Exception e) {
                }
 
               
            }
        }

    }

    private void popBusinessTab() {
        DefaultTableModel model = (DefaultTableModel) tabBusinessView.getModel();
        model.setRowCount(0);

        for (Network nw : system.getNetworkList()) {
            if ("Boston".equals(nw.getNetworkName())) {
                for (Enterprise en : nw.getEntDirObj().getEnterpriseList()) {
                    if (en.getEnterpriseType() == Enterprise.EnterpriseType.BUSINESSENTERPRISE) {
                        BusinessEnterprise busEnt = (BusinessEnterprise) en;
                        ArrayList<Business> businessList = busEnt.getBusinessDir();
                        for (Business bus : businessList) {
                            Object[] row = new Object[5];
                            row[0] = bus.getBusinessId();
                            row[1] = bus.getBusinessName();
                            row[2] = bus.getBusinessDescription();
                            row[3] = bus.getBusinessType();
                            row[4] = bus.getLenderID();
                            if (bus.getOrgType() == Organization.Type.PUBLICBUSINESSPORTFOLIOORG) {
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }

    }
}
