/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Main;

import Business.DB4OUtil.DB4OUtil;
import BusinessReliefPortal.Business.Business;
import BusinessReliefPortal.BusinessReliefSystem;
import BusinessReliefPortal.Employee.Employee;
import BusinessReliefPortal.Enterprise.BusinessEnterprise;
import BusinessReliefPortal.Enterprise.Enterprise;
import BusinessReliefPortal.Enterprise.FundManagementEnterprise;
import BusinessReliefPortal.Enterprise.UserAndVerificationEnterprise;
import BusinessReliefPortal.Lender.Lender;
import BusinessReliefPortal.Network.Network;
import BusinessReliefPortal.Organization.Organization;
import BusinessReliefPortal.Organization.TreasuryOrg;
import BusinessReliefPortal.Proposal.Proposal;
import BusinessReliefPortal.Proposal.ProposalDirectory;
import BusinessReliefPortal.WorkRequest.WorkRequest;
import static UserInterface.Main.LenderPage.lenderID;
import java.util.ArrayList;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ishitajanwale
 */
public class TreasurerPage extends javax.swing.JFrame {

    BusinessReliefSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form TreasurerPage
     */
    public TreasurerPage() {
        initComponents();
        system = LoginPage.system;
        //system = dB4OUtil.retrieveSystem();
        txtAmountToBeAdded.setText("0");

        popFunds();
     //   popProposals();

        popWorkReq();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panAddFunds = new javax.swing.JPanel();
        lblAmountToBeAdded = new javax.swing.JLabel();
        txtAmountToBeAdded = new javax.swing.JTextField();
        AddFundsbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEssPercent = new javax.swing.JTextField();
        sliSplitFunds = new javax.swing.JSlider();
        lblEssPercent = new javax.swing.JLabel();
        lblNonEssPercent = new javax.swing.JLabel();
        txtNonEssPercent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panViewFunds = new javax.swing.JPanel();
        lblTotalFunds = new javax.swing.JLabel();
        txtTotalFunds = new javax.swing.JTextField();
        lblNonEssFunds = new javax.swing.JLabel();
        txtEssFunds = new javax.swing.JTextField();
        txtNonEssFunds = new javax.swing.JTextField();
        lblEssFunds = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelWorkRequests = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabWorkRequests = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jTabbedPane1.setForeground(new java.awt.Color(0, 138, 185));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jTabbedPane1.setRequestFocusEnabled(false);
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        panAddFunds.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panAddFunds.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAmountToBeAdded.setBackground(new java.awt.Color(255, 255, 255));
        lblAmountToBeAdded.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAmountToBeAdded.setForeground(new java.awt.Color(0, 138, 185));
        lblAmountToBeAdded.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAmountToBeAdded.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/outcome.png"))); // NOI18N
        lblAmountToBeAdded.setText("Amount to be added to Treasury");
        panAddFunds.add(lblAmountToBeAdded, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 420, 140));

        txtAmountToBeAdded.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtAmountToBeAdded.setForeground(new java.awt.Color(0, 141, 188));
        txtAmountToBeAdded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountToBeAddedActionPerformed(evt);
            }
        });
        txtAmountToBeAdded.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAmountToBeAddedKeyPressed(evt);
            }
        });
        panAddFunds.add(txtAmountToBeAdded, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 240, 30));

        AddFundsbtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        AddFundsbtn.setForeground(new java.awt.Color(0, 141, 188));
        AddFundsbtn.setText("Add");
        AddFundsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFundsbtnActionPerformed(evt);
            }
        });
        panAddFunds.add(AddFundsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 240, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 138, 185));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/split (1).png"))); // NOI18N
        jLabel1.setText("Split % between type of Funds:");
        panAddFunds.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 410, 150));

        txtEssPercent.setEditable(false);
        txtEssPercent.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtEssPercent.setForeground(new java.awt.Color(0, 141, 188));
        txtEssPercent.setText("70");
        panAddFunds.add(txtEssPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 250, 30));

        sliSplitFunds.setBackground(new java.awt.Color(102, 0, 204));
        sliSplitFunds.setPaintLabels(true);
        sliSplitFunds.setPaintTicks(true);
        sliSplitFunds.setSnapToTicks(true);
        sliSplitFunds.setValue(70);
        sliSplitFunds.setPreferredSize(new java.awt.Dimension(250, 40));
        sliSplitFunds.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliSplitFundsStateChanged(evt);
            }
        });
        panAddFunds.add(sliSplitFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 240, 60));

        lblEssPercent.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEssPercent.setForeground(new java.awt.Color(0, 138, 185));
        lblEssPercent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEssPercent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/essential.png"))); // NOI18N
        lblEssPercent.setText("Essential Funds %:");
        panAddFunds.add(lblEssPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 320, 90));

        lblNonEssPercent.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNonEssPercent.setForeground(new java.awt.Color(0, 138, 185));
        lblNonEssPercent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNonEssPercent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/review.png"))); // NOI18N
        lblNonEssPercent.setText("Non Essential Funds %:");
        panAddFunds.add(lblNonEssPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 330, 90));

        txtNonEssPercent.setEditable(false);
        txtNonEssPercent.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtNonEssPercent.setForeground(new java.awt.Color(0, 141, 188));
        txtNonEssPercent.setText("30");
        txtNonEssPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNonEssPercentActionPerformed(evt);
            }
        });
        panAddFunds.add(txtNonEssPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 250, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 171, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/istockphoto-1281736074-612x612 (1).jpg"))); // NOI18N
        panAddFunds.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, 1140));

        jButton1.setText("jButton1");
        panAddFunds.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        jTabbedPane1.addTab("Add Funds", panAddFunds);

        panViewFunds.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalFunds.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTotalFunds.setForeground(new java.awt.Color(0, 138, 185));
        lblTotalFunds.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTotalFunds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/saving.png"))); // NOI18N
        lblTotalFunds.setText("Total Funds in Treasury:");
        panViewFunds.add(lblTotalFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 280, 80));

        txtTotalFunds.setEditable(false);
        txtTotalFunds.setBackground(new java.awt.Color(0, 141, 188));
        txtTotalFunds.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtTotalFunds.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalFundsActionPerformed(evt);
            }
        });
        txtTotalFunds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalFundsKeyPressed(evt);
            }
        });
        panViewFunds.add(txtTotalFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 270, 40));

        lblNonEssFunds.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblNonEssFunds.setForeground(new java.awt.Color(0, 138, 185));
        lblNonEssFunds.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNonEssFunds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dress.png"))); // NOI18N
        lblNonEssFunds.setText("Non-Essential Funds:");
        panViewFunds.add(lblNonEssFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 260, 70));

        txtEssFunds.setEditable(false);
        txtEssFunds.setBackground(new java.awt.Color(0, 141, 188));
        txtEssFunds.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtEssFunds.setForeground(new java.awt.Color(255, 255, 255));
        panViewFunds.add(txtEssFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 270, 40));

        txtNonEssFunds.setEditable(false);
        txtNonEssFunds.setBackground(new java.awt.Color(0, 141, 188));
        txtNonEssFunds.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtNonEssFunds.setForeground(new java.awt.Color(255, 255, 255));
        panViewFunds.add(txtNonEssFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 270, 40));

        lblEssFunds.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblEssFunds.setForeground(new java.awt.Color(0, 138, 185));
        lblEssFunds.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEssFunds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/essential (2).png"))); // NOI18N
        lblEssFunds.setText("Essential Funds:");
        panViewFunds.add(lblEssFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 290, 70));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 138, 185));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-template-background-white-and-bright-blue-squares-overlapping-with-halftone-and-texture-free-vector (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        panViewFunds.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1010, 1000));

        jTabbedPane1.addTab("View Funds", panViewFunds);

        panelWorkRequests.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabWorkRequests.setBackground(new java.awt.Color(0, 141, 188));
        tabWorkRequests.setForeground(new java.awt.Color(255, 255, 255));
        tabWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Work Rquest Id", "Sender", "Receiver", "Sender Org", "Receiver Org", "Message", "Status"
            }
        ));
        jScrollPane6.setViewportView(tabWorkRequests);

        panelWorkRequests.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 992, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-template-background-white-and-bright-blue-squares-overlapping-with-halftone-and-texture-free-vector (1).jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        panelWorkRequests.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 1010, 970));

        jTabbedPane1.addTab("WorkRequest", panelWorkRequests);

        jPanel1.setBackground(new java.awt.Color(0, 141, 188));

        btnLogOut.setBackground(new java.awt.Color(0, 162, 216));
        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout (3).png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Treasurer's Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalFundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFundsActionPerformed

    private void AddFundsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFundsbtnActionPerformed
        // TODO add your handling code here:
        if (txtAmountToBeAdded.getText().equals("") || txtAmountToBeAdded.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter valid funds");
            return;
        }
        if (!txtAmountToBeAdded.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter valid funds");
            return;
        }
        
        Organization selectedOrganization;

        for (Network nw : system.getNetworkList()) {
            if ("Boston".equalsIgnoreCase(nw.getNetworkName())) {
                for (Enterprise en : nw.getEntDirObj().getEnterpriseList()) {
                    if (en.getEnterpriseType() == Enterprise.EnterpriseType.FUNDMANAGEMENTENTERPRISE) {
                        for (Organization org : en.getOrganizationDirectory().getOrganizationList()) {
                            if (org.getOrgType() == Organization.Type.TREASURYORG) {
                                TreasuryOrg treasury = (TreasuryOrg) org;
                                float totalFunds = treasury.getTotalfunds();

                                totalFunds = treasury.addToTotalfunds(Float.parseFloat(txtAmountToBeAdded.getText()), sliSplitFunds.getValue());
                                txtAmountToBeAdded.setText("0");

                                txtTotalFunds.setText(String.valueOf(treasury.getTotalfunds()));
                                txtEssFunds.setText(String.valueOf(treasury.getEssentialfunds()));
                                txtNonEssFunds.setText(String.valueOf(treasury.getNonessentialfunds()));

                                return;
                            }
                        }

                    }
                }
            }
        }
//        selectedOrganization.
    }//GEN-LAST:event_AddFundsbtnActionPerformed

    private void txtAmountToBeAddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountToBeAddedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountToBeAddedActionPerformed

    private void sliSplitFundsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliSplitFundsStateChanged
        // TODO add your handling code here:
        int percentage = sliSplitFunds.getValue();
        txtEssPercent.setText("" + percentage);
        txtNonEssPercent.setText("" + (100 - percentage));
    }//GEN-LAST:event_sliSplitFundsStateChanged

    private void txtNonEssPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNonEssPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNonEssPercentActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //system.
        for (Network nw : system.getNetworkList()) {
            if ("Boston".equalsIgnoreCase(nw.getNetworkName())) {
                for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
                    for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getOrgType() == Organization.Type.TREASURYORG) {
                            TreasuryOrg treasury = (TreasuryOrg) org;
                            txtTotalFunds.setText(String.valueOf(treasury.getTotalfunds()));
                            txtEssFunds.setText(String.valueOf(treasury.essentialFunds));
                            txtNonEssFunds.setText(String.valueOf(treasury.nonessentialFunds));
                            jTabbedPane1.setSelectedIndex(1);

                            txtAmountToBeAdded.setText("0");

                            return;
                        }
                    }

                }
            }
        }

//        TreasuryOrg treasury = new TreasuryOrg();
//        float totalFunds = treasury.getTotalfunds();
//
//        txtTotalFunds.setText(String.valueOf(treasury.getTotalfunds()));
//        txtEssFunds.setText(String.valueOf(treasury.essentialFunds));
//        txtNonEssFunds.setText(String.valueOf(treasury.nonessentialFunds));
//        jTabbedPane1.setSelectedIndex(1);
//
//        txtAmountToBeAdded.setText("0");

    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void txtTotalFundsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalFundsKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalFundsKeyPressed

    private void txtAmountToBeAddedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountToBeAddedKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtAmountToBeAdded.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "Please enter numeric values only");
        } else {
            txtAmountToBeAdded.setEditable(true);
        }
    }//GEN-LAST:event_txtAmountToBeAddedKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If NimpanDeductFundstroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreasurerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreasurerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreasurerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreasurerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreasurerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFundsbtn;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAmountToBeAdded;
    private javax.swing.JLabel lblEssFunds;
    private javax.swing.JLabel lblEssPercent;
    private javax.swing.JLabel lblNonEssFunds;
    private javax.swing.JLabel lblNonEssPercent;
    private javax.swing.JLabel lblTotalFunds;
    private javax.swing.JPanel panAddFunds;
    private javax.swing.JPanel panViewFunds;
    private javax.swing.JPanel panelWorkRequests;
    private javax.swing.JSlider sliSplitFunds;
    private javax.swing.JTable tabWorkRequests;
    private javax.swing.JTextField txtAmountToBeAdded;
    private javax.swing.JTextField txtEssFunds;
    private javax.swing.JTextField txtEssPercent;
    private javax.swing.JTextField txtNonEssFunds;
    private javax.swing.JTextField txtNonEssPercent;
    private javax.swing.JTextField txtTotalFunds;
    // End of variables declaration//GEN-END:variables

    public void popWorkReq() {
        DefaultTableModel model = (DefaultTableModel) tabWorkRequests.getModel();
        model.setRowCount(0);
        for (Network nw : system.getNetworkList()) {
            if ("Boston".equalsIgnoreCase(nw.getNetworkName())) {

                for (Enterprise ent : nw.getEntDirObj().getEnterpriseList()) {
                    if (ent.getEnterpriseType() == Enterprise.EnterpriseType.FUNDMANAGEMENTENTERPRISE) {
                        FundManagementEnterprise fme = (FundManagementEnterprise) ent;
                        // Employee treasurer = fme.getEmployeeDirectory().get(1);
                        //  Map<Integer, WorkRequest> personWorkQueue = treasurer.getPersonWorkQueue();
                        Map<Integer, Employee> employeeDirectory = fme.getEmployeeDirectory();
                        Employee treasurer = employeeDirectory.get(1);
                        Map<Integer, WorkRequest> personWorkQueue = treasurer.getPersonWorkQueue();

                        for (Map.Entry<Integer, WorkRequest> entry : personWorkQueue.entrySet()) {
                            Object key = entry.getKey();
                            Object val = entry.getValue();

                            Object[] row = new Object[7];

                            row[0] = entry.getKey();
                            row[1] = entry.getValue().getSender();
                            row[2] = entry.getValue().getReceiver();
                            row[3] = entry.getValue().getSenderOrg();
                            row[4] = entry.getValue().getReceiverOrg();
                            row[5] = entry.getValue().getMessage();
                            row[6] = entry.getValue().getStatus();

                            model.addRow(row);

                        }

                    }
                }

            }
        }
    }

//    public void popProposals() {
//        DefaultTableModel model = (DefaultTableModel) tabProposals.getModel();
//        model.setRowCount(0);
//
//        for (Network nw : system.getNetworkList()) {
//            if ("Boston".equalsIgnoreCase(nw.getNetworkName())) {
//                ProposalDirectory proposalDirectory = nw.getProposalDirectory();
//                for (Proposal prop : proposalDirectory.getProposalDirectory()) {
//
//                    if ("Funds Requested".equalsIgnoreCase(prop.getProposalStatus())) {
//
//                        Object[] row = new Object[6];
//                        row[0] = prop.getProposalId();
//                        row[1] = prop.getFunderId();
//                        row[2] = prop.getBusinessIdByFunder();
//                        row[3] = prop.getBorrower().getBorrowerId();
//                        row[4] = prop.getBorrower().getRequestedFund();
//                        row[5] = prop.getProposalStatus();
//
//                        model.addRow(row);
//
//                    }
////                 
//                }
//            }
//        }
//    }

    private void popFunds() {
        for (Network nw : system.getNetworkList()) {
            if ("Boston".equalsIgnoreCase(nw.getNetworkName())) {
                for (Enterprise en : nw.getEntDirObj().getEnterpriseList()) {
                    if (en.getEnterpriseType() == Enterprise.EnterpriseType.FUNDMANAGEMENTENTERPRISE) {
                        for (Organization org : en.getOrganizationDirectory().getOrganizationList()) {
                            if (org.getOrgType() == Organization.Type.TREASURYORG) {
                                TreasuryOrg treasury = (TreasuryOrg) org;

                                txtTotalFunds.setText(String.valueOf(treasury.getTotalfunds()));
                                txtEssFunds.setText(String.valueOf(treasury.getEssentialfunds()));
                                txtNonEssFunds.setText(String.valueOf(treasury.getNonessentialfunds()));

                                return;
                            }
                        }

                    }
                }
            }
        }
    }
}
